Fix errors C7555 & C4576 on MSVC
error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
error C7555: use of designated initializers requires at least '/std:c++20'